node {
   stage('Stage 1'){
   		echo 'Hello World 1'
   }
   stage('Stage 2'){
   		echo 'Hello World 2'
   }
   stage('Checkout'){
		git url: 'https://github.com/anotherik/Test-Suite-Tools.git'
   }
   stage('PWD'){
   		pwd
   }
   stage('Build'){ 
		sh 'Jenkins/Pipeline-Example/build.sh'
   }
   stage('Test'){ 
		sh 'Jenkins/Pipeline-Example/test.sh'
   }
}
